"""
Django settings for aiotautotech_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path

# ==============================================================================
# 1. CẤU HÌNH CƠ BẢN & BIẾN MÔI TRƯỜNG
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Lấy SECRET_KEY từ biến môi trường (bắt buộc phải set khi chạy Production)
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-default-key-for-local-dev-fallback",  # chỉ dùng local/dev
)

# Xác định đang chạy trên Cloud Run hay không
# Cloud Run tự set biến môi trường K_SERVICE
IS_CLOUD_RUN = bool(os.environ.get("K_SERVICE"))

# Khi chạy trên Cloud Run → DEBUG = False
DEBUG = not IS_CLOUD_RUN

# ALLOWED_HOSTS
if IS_CLOUD_RUN:
    # Trên Cloud Run, thường đặt '*' (vì Cloud Run đã đứng trước với HTTPS/Proxy)
    # Nếu muốn chặt hơn, bạn có thể set cụ thể domain sau này.
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ==============================================================================
# 2. CẤU HÌNH CLOUD FIRESTORE (KHÔNG DÙNG FILE JSON)
# ==============================================================================

# Nên set FIRESTORE_PROJECT_ID qua biến môi trường để linh hoạt:
#   export FIRESTORE_PROJECT_ID="aiotautotech"
FIRESTORE_PROJECT_ID = os.environ.get("FIRESTORE_PROJECT_ID", "aiotautotech")

# Không dùng service account key file ở đây nữa.
# Xác thực sẽ dùng Application Default Credentials (ADC):
#   - Local:   gcloud auth application-default login
#   - Cloud:   gán service account cho Cloud Run
# Việc khởi tạo client thực hiện trong firestore_client.py

# ==============================================================================
# 2.1. CẤU HÌNH CLOUDFLARE R2 (UPLOAD ẢNH SẢN PHẨM)
# ==============================================================================

# Các biến này dùng cho module upload R2 (boto3 client)
# Nên set trong Cloud Run:
#   R2_BUCKET_NAME, R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY
#   R2_PUBLIC_BASE_URL: domain CDN public, ví dụ: https://cdn.aiotautotech.com
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "aiot-images")
R2_ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID", "")
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "")

# Domain public dùng để build URL ảnh trả về cho frontend
R2_PUBLIC_BASE_URL = os.environ.get(
    "R2_PUBLIC_BASE_URL",
    "https://cdn.aiotautotech.com",  
)

# ==============================================================================
# 3. APPS & MIDDLEWARE
# ==============================================================================

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",

    # Local
    "core_api",
]

MIDDLEWARE = [
    # CORS nên đặt ở rất cao để bắt preflight (OPTIONS)
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aiotautotech_backend.urls"

# ==============================================================================
# 4. CẤU HÌNH CORS – TÁCH RÕ LOCAL VS CLOUD RUN
# ==============================================================================

# 4.1. Xác định các origin được phép
if IS_CLOUD_RUN:
    # Trên Cloud Run:
    # Ưu tiên dùng FRONTEND_ORIGINS: danh sách origin, ngăn cách bởi dấu phẩy
    #   VD:
    #   FRONTEND_ORIGINS="https://url1,https://url2"
    raw_origins = os.environ.get("FRONTEND_ORIGINS", "")

    if raw_origins:
        FRONTEND_ORIGINS = [
            o.strip().rstrip("/") for o in raw_origins.split(",") if o.strip()
        ]
    else:
        # Backward-compatible: nếu chưa dùng FRONTEND_ORIGINS thì vẫn đọc FRONTEND_ORIGIN
        FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", "").rstrip("/")
        FRONTEND_ORIGINS = [FRONTEND_ORIGIN] if FRONTEND_ORIGIN else []
else:
    # Local dev: chỉ cho phép frontend chạy ở localhost:3000
    FRONTEND_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]


# 4.2. Cấu hình CORS mặc định: KHÔNG cho tất cả origin, chỉ cho danh sách rõ ràng
CORS_ALLOW_ALL_ORIGINS = False

# Lọc bỏ chuỗi rỗng (phòng khi FRONTEND_ORIGIN chưa set trên Cloud Run)
CORS_ALLOWED_ORIGINS = [o for o in FRONTEND_ORIGINS if o]

# Tuỳ chọn: mở full CORS trên Cloud Run khi debug,
#   chỉ nên dùng tạm thời:
#   CORS_ALLOW_ALL="1"
if IS_CLOUD_RUN and os.environ.get("CORS_ALLOW_ALL") == "1":
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []  # không cần khi đã cho phép tất cả

# 4.3. Các option CORS khác

# Nếu sau này bạn dùng cookie/session từ frontend, để True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Header mà frontend có thể đọc được
CORS_EXPOSE_HEADERS = [
    "Content-Type",
]

# ==============================================================================
# 5. TEMPLATES
# ==============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aiotautotech_backend.wsgi.application"

# ==============================================================================
# 6. STATIC FILES
# ==============================================================================

STATIC_URL = "static/"

# Thư mục đích cho collectstatic (phù hợp với Cloud Run)
STATIC_ROOT = BASE_DIR / "staticfiles"

# ==============================================================================
# 7. NGÔN NGỮ, TIMEZONE, PRIMARY KEY
# ==============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
