"""
Django settings for aiotautotech_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path

# ==============================================================================
# 1. CẤU HÌNH CƠ BẢN VÀ BIẾN MÔI TRƯỜNG
# ==============================================================================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lấy SECRET_KEY từ biến môi trường (Bắt buộc cho Production)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-local-dev-fallback')

# Xác định môi trường Production: K_SERVICE là biến môi trường do Cloud Run cung cấp.
IS_CLOUD_RUN = bool(os.environ.get('K_SERVICE'))

# SECURITY WARNING: Tắt DEBUG khi triển khai lên Cloud Run
DEBUG = not IS_CLOUD_RUN 


# Cấu hình ALLOWED_HOSTS
if IS_CLOUD_RUN:
    # Nếu chạy trên Cloud Run, chấp nhận tất cả hostnames (An toàn khi DEBUG=False)
    ALLOWED_HOSTS = ['*']
else:
    # Môi trường Local
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ==============================================================================
# 2. CẤU HÌNH CLOUD FIRESTORE
# ==============================================================================

FIRESTORE_PROJECT_ID = 'aiotautotech'
# Nếu bạn đã gán Service Account cho Cloud Run, bạn không cần file key.
# Nếu bạn cần file key trong môi trường local, hãy giữ lại các dòng sau:
FIRESTORE_KEY_FILE = 'aiotautotech-42240dcf71e4.json'
FIRESTORE_CREDENTIALS_PATH = BASE_DIR / FIRESTORE_KEY_FILE


# ==============================================================================
# 3. CẤU HÌNH ỨNG DỤNG VÀ MIDDLEWARE
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders', 
    
    # Local apps
    'core_api', 
]

MIDDLEWARE = [
    # CORS phải được đặt ở đầu để xử lý các yêu cầu preflight (OPTIONS)
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aiotautotech_backend.urls'

# ==============================================================================
# 4. CẤU HÌNH CORS (Giải quyết lỗi Failed to fetch)
# ==============================================================================

# Lấy URL của Frontend Cloud Run từ biến môi trường (Nếu bạn thiết lập)
# Tên dịch vụ Cloud Run Frontend của bạn
FRONTEND_SERVICE_NAME = 'aiotautotech-frontend' 
FRONTEND_REGION = 'asia-southeast1' # Vùng triển khai Frontend

if IS_CLOUD_RUN:
    # # Production: Cho phép Frontend Cloud Run và Frontend Local truy cập
    # CORS_ALLOW_ALL_ORIGINS = False # Tắt tính năng cho phép tất cả, sử dụng danh sách rõ ràng
    
    # # Xây dựng URL Frontend Cloud Run để cho phép nó truy cập Backend
    # FRONTEND_CLOUD_RUN_URL = f"https://{FRONTEND_SERVICE_NAME}-{FIRESTORE_PROJECT_ID}.{FRONTEND_REGION}.run.app"
    
    # CORS_ALLOWED_ORIGINS = [
    #     # Cho phép Frontend đã triển khai truy cập Backend
    #     FRONTEND_CLOUD_RUN_URL,
        
    #     # Thêm địa chỉ local để nếu bạn chạy Production build local, nó vẫn hoạt động
    #     "http://localhost:3000",
    #     "http://127.0.0.1:3000",
    # ]
    CORS_ALLOW_ALL_ORIGINS = True 
    CORS_ALLOWED_ORIGINS = []
else:
    # Local Development: Chỉ cho phép nguồn gốc Next.js local
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# Cấu hình Headers và Methods cần thiết (Giữ nguyên)
CORS_ALLOW_HEADERS = [
    'accept',
    # ... (Các tiêu đề khác) ...
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'POST',
    'PUT',
]

# ==============================================================================
# 5. CẤU HÌNH TEMPLATES
# ==============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aiotautotech_backend.wsgi.application'

# ==============================================================================
# 6. CẤU HÌNH STATIC FILES (BẮT BUỘC)
# ==============================================================================

# URL mà Django sẽ sử dụng để phục vụ các tệp tĩnh
STATIC_URL = 'static/'

# Đường dẫn vật lý nơi các tệp tĩnh sẽ được thu thập khi chạy 'collectstatic'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ... (Các cấu hình khác: LANGUAGE_CODE, TIME_ZONE, STATIC_URL giữ nguyên) ...
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'