# Generated by Django 5.2.8 on 2025-11-24 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('bundle', 'Bundle / Kit'), ('service', 'Service')], default='simple', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá cơ bản của sản phẩm (VND).', max_digits=12, null=True)),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('sku', models.CharField(blank=True, help_text='Mã SKU nội bộ, dùng cho quản lý kho.', max_length=64)),
                ('stock_tracking', models.BooleanField(default=True, help_text='Có theo dõi tồn kho cho sản phẩm này hay không.')),
                ('stock_qty', models.PositiveIntegerField(default=0, help_text='Số lượng tồn kho hiện tại (nếu có theo dõi).')),
                ('min_order_qty', models.PositiveIntegerField(default=1, help_text='Số lượng tối thiểu khi đặt hàng.')),
                ('tags', models.CharField(blank=True, help_text='Tags, ngăn cách bởi dấu phẩy.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_optional', models.BooleanField(default=False, help_text='Nếu True thì item này có thể bỏ chọn khi cấu hình kit.')),
                ('is_default', models.BooleanField(default=True, help_text='Nếu False thì item này không được chọn sẵn.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị trong danh sách sản phẩm con.')),
                ('note', models.CharField(blank=True, help_text="Ghi chú hiển thị (ví dụ: 'Có thể thay cảm biến khác').", max_length=255)),
                ('child_product', models.ForeignKey(help_text='Sản phẩm con thuộc bộ.', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='core_api.product')),
                ('parent_product', models.ForeignKey(help_text='Sản phẩm cha (bundle/kit).', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_api.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
