# Generated by Django 5.2.8 on 2025-11-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_urls',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách URL ảnh phụ (gallery).', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Ảnh chính của sản phẩm (URL, thường từ CDN/R2).', max_length=500),
        ),
    ]
